### ISSUE TITLE
Control surface messages

### ISSUE THREAD

**Issue by tbarbe004** [iscore-pfa/qml-remote#7]
Hello,

We tried to receive correctly the messages sent by score on our application, to display a control surface when it is reached on score's scenario.

- First, is it possible to receive the message that give the name of the control surface ? We think it would be more pleasant for the user to see the name of the control surface instead of the path.

- We also observed a problem when we are restarting the scenario : when we stop the scenario while a control surface interval do not finish, there is not problem. But when we stop it after the end of the control surface interval, and then restart, the control surface will appear twice when its interval starts on the application. For now, we are refusing to add a control surface that has the same name than another one already displayed on the application to avoid the problem.

**Comment by jcelerier** [comment]
looking into it
