### ISSUE TITLE
Needed message from score to client

### ISSUE THREAD

**Issue by EloiMagon** [iscore-pfa/qml-remote#8]
@jcelerier 
In order to update the appearance of the button play pause in the interface, we'd need score to send a message containing its state (playing or paused), when one of this button is pressed in score.

**Comment by jcelerier** [comment]
done in https://github.com/ossia/score/commit/cad6ece5a6d336f8209035bf02da8c9a5c990121 - the new messages are called IntervalPaused / IntervalResumed

**Comment by jcelerier** [comment]
(you have to check that the "top" interval is being paused / resume as various subparts of the score can be)
